/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FortschrittRouteImport } from './routes/fortschritt'
import { Route as ThemenRouteImport } from './routes/themen'
import { Route as ThemaIdRouteImport } from './routes/thema.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FortschrittRoute = FortschrittRouteImport.update({
  id: '/fortschritt',
  path: '/fortschritt',
  getParentRoute: () => rootRouteImport,
} as any)
const ThemenRoute = ThemenRouteImport.update({
  id: '/themen',
  path: '/themen',
  getParentRoute: () => rootRouteImport,
} as any)
const ThemaIdRoute = ThemaIdRouteImport.update({
  id: '/thema/$id',
  path: '/thema/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/fortschritt': typeof FortschrittRoute
  '/themen': typeof ThemenRoute
  '/thema/$id': typeof ThemaIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/fortschritt': typeof FortschrittRoute
  '/themen': typeof ThemenRoute
  '/thema/$id': typeof ThemaIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/fortschritt': typeof FortschrittRoute
  '/themen': typeof ThemenRoute
  '/thema/$id': typeof ThemaIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/fortschritt' | '/themen' | '/thema/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/fortschritt' | '/themen' | '/thema/$id'
  id: '__root__' | '/' | '/fortschritt' | '/themen' | '/thema/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FortschrittRoute: typeof FortschrittRoute
  ThemenRoute: typeof ThemenRoute
  ThemaIdRoute: typeof ThemaIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fortschritt': {
      id: '/fortschritt'
      path: '/fortschritt'
      fullPath: '/fortschritt'
      preLoaderRoute: typeof FortschrittRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/themen': {
      id: '/themen'
      path: '/themen'
      fullPath: '/themen'
      preLoaderRoute: typeof ThemenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thema/$id': {
      id: '/thema/$id'
      path: '/thema/$id'
      fullPath: '/thema/$id'
      preLoaderRoute: typeof ThemaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FortschrittRoute: FortschrittRoute,
  ThemenRoute: ThemenRoute,
  ThemaIdRoute: ThemaIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
